### ISSUE TITLE
Bond Slides Extend too Far

### ISSUE THREAD

**Issue by jdwallMTU** [jeffreywallphd/OpenFinAL#100]
**Describe the bug**
When you view the Bonds slideshow, some of the slides have too much content on them. It causes the content to bleed outside of the slide window. The amount of content on these slides needs to be reduced or the content needs to be split across multiple slides. Splitting the slides will require you to re-record the audio and change the SQL. If you are able to condense the content, that will be the simplest fix for now.

**To Reproduce**
1. Pull the latest from the main branch
2. In the terminal, run: npm start
3. Go to the Learn section of the application and click the Bonds tutorial
4. Click through the slides. You will see which are too large for the window.

**Expected behavior**
A clear and concise description of what you expected to happen:
The slide content needs to be shortened or split up.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop (please complete the following information):**
 - OS: Windows, likely Mac as well
 - Browser: Electron
 - Browser Version: N/A

**Additional context**

**Comment by jeffreywallphd** [comment]
Due to slide changes and an increased size in the slide window height, this should no longer be a problem.
