### ISSUE TITLE
Max button give 5 day

### ISSUE THREAD

**Issue by Sickmannnnnn** [jeffreywallphd/OpenFinAL#112]
**Describe the bug**
When choosing the max button for historical price data of a stock on the graph on the Stock and Fund page, instead of giving maximum time range, it gives the 5-day.

**To Reproduce**
1. Go to 'Stock and Fund'
2. Click on 'max'

**Expected behavior**
Give max time range, most likely somewhere between 5 and 40 years.
![image](https://github.com/jeffreywallphd/AutoProphet/assets/113903157/e589efb4-85d9-4bc0-8680-8a82b7b9e772)

**Screenshots**
Currently looks like: 
![image](https://github.com/jeffreywallphd/AutoProphet/assets/113903157/be16ca68-fbc2-41bc-b369-d306402c7be0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Electron
 - Browser Version: Current

**Additional context**
This is likely an issue solely with the API, and thus the only solutions may be to switch APIs or remove the max button.

**Comment by jeffreywallphd** [comment]
I found the issue and have created a pull request to fix the issue. Once the pull request is reviewed and approved, I will close this bug.

**Comment by jeffreywallphd** [comment]
This issue is fixed as of a recent pull request. Closing!
