### ISSUE TITLE
Remove vertical lines from Stock & Fund time series chart

### ISSUE THREAD

**Issue by jeffreywallphd** [jeffreywallphd/OpenFinAL#145]
**Is your feature request related to a problem? Please describe.**
The vertical lines on the price chart are not consistent and don't add particular value. Many other chart providers do not have the vertical dotted lines. 

**Describe the solution you'd like**
Remove the vertical dotted lines and retain only the horizontal lines.

**Describe alternatives you've considered**
Simple enough that it does not require alternatives.

**Additional context**
This will be accomplished by adjusting ReCharts parameters in the TimeSeriesChart.jsx View file.

**Comment by Kamitoad** [comment]
I want to contribute on this issue, already forked the project to see what has to be done and immediately found a solution to make it appear like in the Image below:

What can I do to make a pull request to help?

![image](https://github.com/jeffreywallphd/AutoProphet/assets/90114314/6fa63d0e-7d9a-4722-acd7-90207e851d04)

**Comment by jeffreywallphd** [comment]
@Kamitoad please send me an email to my faculty account at jdwall@mtu.edu. I am not familiar with your username. This repository is largely designed to support student learning. Please message me with your .edu email so I know who is making this request.

Best,
Jeff

**Comment by Kamitoad** [comment]
Hey @jeffreywallphd I am glad to hear from you, I sent you an email with the email account of my university.

**Comment by jeffreywallphd** [comment]
Thanks for the contribution. It looks much cleaner.
