### ISSUE TITLE
Import Never Used - App.jsx

### ISSUE THREAD

**Issue by tsheets04** [jeffreywallphd/OpenFinAL#48]
It looks like the code on line 9 of "App.jsx" is redundant, however I don't want to remove it if it is there for a reason I am not aware of. It contains:

`import * as ReactDOM from 'react-dom';`

There are other imports that import similar modules, but I am not sure if they are the same.

**Comment by jeffreywallphd** [comment]
Yes, this is true. I have a branch that I'm working on where I removed this unused import. In another day or two, I will make a pull request for the branch and it will fix this unused import. Please let me know if you run into others like this. I'm trying to remove those as I go, but I'm sure I will miss some. Thanks for your attention to detail!

**Comment by jeffreywallphd** [comment]
I will close this after my next pull request is merged. Don't worry for now.

**Comment by jeffreywallphd** [comment]
This is now resolved. Thanks for identifying the unused import.
