### ISSUE TITLE
Props usage issue

### ISSUE THREAD

**Issue by tsheets04** [jeffreywallphd/OpenFinAL#61]
I am trying to add the ratios to the sidebar and I am having some troubles with using props. I am not entirely sure what the issue is so I can't look it up myself. My branch (TempTS) should have the updated Ratios.jsx file where the problem is occurring. Any help/direction is appreciated.

**Comment by jeffreywallphd** [comment]
@tsheets04 you needed a way to pass the data from the props into the Ratios file. I used your logic to create a RatiosCalculator class that I put in the Utility folder. In the file, all of the ratios you had are calculated and pushed into the class variables with the same names as the data you were exporting in your previous file. The props data is pushed into the instantiation of the RatiosCalculator within the TickerSidePanel file. Your branch was out of date, so I also merged it with main. I made the commits and pushed it to the branch. You should be able to run a git pull from the TempTS branch and you will see the changes outlined above. You can go into the RatioCalculator.ts file and start adding more of the data from the SEC API results. I hope that helped and makes sense. Let me know if you have any follow up questions.

**Comment by tsheets04** [comment]
Thank you! I would have been lost for a while on the pace I was going. I will continue to add the API results.
