### ISSUE TITLE
Learn slideshows intermittently throw error because pages aren't loaded

### ISSUE THREAD

**Issue by jeffreywallphd** [jeffreywallphd/OpenFinAL#73]
The Learn slideshow intermittently throws and error because either the database or the state information has not populated to the slide before it is called. A useEffect() method, or something similar, could be used to ensure that the slide data is handled after other features/data are available for use. This should be a simple fix, but the slideshow prototype was implemented for others to begin adding to.

**Comment by jdwallMTU** [comment]
I have not noticed this behavior is a while. For now, I will leave this issue open.

**Comment by jeffreywallphd** [comment]
This has been fixed through previous pull requests.
